Support building upstream latest release from the website
This patch implements override-pull scriptlet to parse and download the
latest release tarball from the upstream website automatically.

The javascript support has been dropped due to FTBFS:

```
../jsint.c:39:10: fatal error: struct.h: no such file or directory
 #include "struct.h"
```

and apparently no one else in the world[1][2] has enable it.

[1] https://src.fedoraproject.org/rpms/links/blob/master/f/links.spec
[2] https://salsa.debian.org/debian/links2/blob/master/debian/rules

Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>